### ISSUE TITLE
Name and Note in Full Description tab should display only once, like Subject

### ISSUE THREAD

**Issue by lydiam** [FLVC/islandoratheme#12]
Currently if multiple subjects are contained in MODS the Full Description displays the label "Subject" only once.  We'd like the same mechanism to be implemented for "Name" and "Note".

**Comment by lydiam** [comment]
It appears that FSU may be requesting that notes with displayLabels that are identical should display with only one Label, taken from displayLabel.  An example is: http://purl.flvc.org/fsu/fd/FSUML-CSMC-H3689, where notes with @displayLabel that are identical display with two labels:

Instrumentation: 	voice
Instrumentation: 	piano 

I believe that Krystal is asking for them to display as:

Instrumentation: 	voice
                        	piano 

Mike will confirm, and if that's the case he'll email ISG to ask if this is what the group wants.  If so, we'll put this in the queue for implementation.

**Comment by lydiam** [comment]
Issue being reopened.

**Comment by mdemers** [comment]
moved to production 4-15-15.
