### ISSUE TITLE
Full MODS form: can "Start Date" and "End Date" be displayed 

### ISSUE THREAD

**Issue by lydiam** [FLVC/islandoratheme#13]
Per the Full MODS forms, dates in the Full Description tab should be displayed as follows:

"For all dates, if there are no @POINT, just display the date following the label.  If @POINT = "start"  display date with a hyphen following, e.g. 1920-.  If @point= "end" display after the date with  a hyphen preceding, e.g. "-1924".  However, if both start and end dates, have only one hyphen between them."

This seems to be implemented only for Date Issued.  See https://islandora7t.fcla.edu/islandora/object/islandora%3A2236# for examples of dates that aren't displaying properly.  

(Reported by Krystal Thomas at FSU via CAS-40826-V5M9).

**Comment by glewisorg** [comment]
Date elements are repeatable.  Is it reasonable to assume that there will be at most two for each kind of date element, like at most two dateCreated, at most two dateModified, and so on?  Otherwise, it would be difficult (in code) to determine what constitutes a "pair" of dates.

**Comment by lydiam** [comment]
I think that's a safe assumption.

**Comment by glewisorg** [comment]
I changed the date display logic on dev.  I decided against the assumption of at most two since more are allowed.

If there is a start/end pairing within a date element sequence, the dates display together with the hyphen in between.  Otherwise, @point=start adds a trailing hyphen, @point=end adds a preceding hyphen, and if there is no @point, it displays only the date.

**Comment by lydiam** [comment]
That sounds good.  I’ll test it.

**Comment by lydiam** [comment]
The fix works with the MODS from my sample record, which I uploaded to the following object: http://islandora7d.fcla.edu/islandora/object/islandora%3A4527  I've contacted Krystal at FSU for some examples that she's encountered for an additional test, but this is probably fine to move to test.

**Comment by lydiam** [comment]
Krystal sent me one of her examples and I uploaded that MODS file to http://islandora7d.fcla.edu/islandora/object/islandora%3A4561

The Date Created date is correct.

**Comment by glewisorg** [comment]
This has moved to test.

**Comment by glewisorg** [comment]
Moved to production on 1/11/15.

**Comment by lydiam** [comment]
Follow-up from Krystal:

Lydia,

Sorry to just get to testing this now. It seems to be working well. My one question: Date Issued is supposed to appear on the summary tab however when I put a date range under date issued, it is not appearing on the Summary tab. However, when I went to make sure that was correct, it’s not appearing on any Summary tab any longer either on test or production. Did that get changed at some point recently?

Krystal

**Comment by lydiam** [comment]
We don't have up-to-date documentation of the Summary display tab, but I do seem to recall that Abstract and Date Issued appeared there.

**Comment by glewisorg** [comment]
This was my test object on dev.  It displays "Date Issued".  Is there an example object where it is not displaying?

http://islandora7d.fcla.edu/islandora/object/islandora%3A4565

**Comment by lydiam** [comment]
It’s not displaying in the Summary Tab, at the bottom (at least not for me in FireFox).  It is displaying in Full Description, and Full Description is what I tested.

Lydia

**Comment by lydiam** [comment]
Favenzio,

Could you take a look to try to determine why Date Issued no longer displays in the Summary tab?

**Comment by Favenzio** [comment]
I put in a fix in dev. If somebody could test it and let me know if it looks correct, I will move it to test for further testing.

**Comment by lydiam** [comment]
What I’m seeing in Dev is that Date Issued:  is appearing toward the top of the Summary tab, on the right-hand side for this object http://islandora7d.fcla.edu/islandora/object/islandora%3A4565# (it’s part of a compound object, so that may be atypical.  My recollection was that it displayed at the bottom of the summary tab, along with Description.  I’ve added a Description field to this object and it’s not displaying, either.

In a book object it’s displaying at the bottom:  http://islandora7d.fcla.edu/islandora/object/islandora%3A4527.  Display at the bottom seems correct, next to the description field.

So it looks like the display is fixed for objects that aren’t compound objects but has some problems with Compound Objects.  I’m wondering if Gail’s text object isn’t part of an odd compound object.  I’d have to research what the Compound Object Summary tab was supposed to look like.

Lydia

**Comment by Favenzio** [comment]
I think Compound Objects where never really 'themed'. I was never given a spec for what they should look like. That could be the reason why it doesn't look the way you expect.
