### ISSUE TITLE
Add title to Name as Subject

### ISSUE THREAD

**Issue by mdemers** [FLVC/islandoratheme#16]
titleInfo/title can now exist within a subject/name element. Please add titleInfo/title values to display in the name as subject string (name_value?)

Ex:
```
<subject>
  <name type="personal" authority="lcsh">
    <namePart>Bob Dole</namePart>
    <namePart type="date">1600-1700</namePart>
    <titleInfo>
       <title>Are you there Gerald? It's me Bob.</title>
    </titleInfo>
   </name>
</subject> 
```
Should display as " Subject(s): Bob Dole, 1600-1700--Are you there Gerald? It's me Bob. "

**Comment by lydiam** [comment]
Can we push on this to get it completed?  I'm trying to close out older CRM cases, per a meeting with Mike Neff.

**Comment by glewisorg** [comment]
Done on dev.  Let me know if it can go to test.

**Comment by mdemers** [comment]
There's a leading space in the query string. There should also be spaces on both sides of the "--" in the subject divisions in both the display and query (I didn't spec that out right). Other than that it's looking good.

**Comment by glewisorg** [comment]
I added spaces around "--".  The leading space in subject->name was there before.  It's not causing problems but if you want it corrected, I can take a look later.

**Comment by glewisorg** [comment]
I think I removed the leading space.  Someone should check that.  I've moved these changes to test.

**Comment by mdemers** [comment]
Leading space is gone. You're right, it wasn't causing any problems anyway. Everything appears to be working well on test.

**Comment by glewisorg** [comment]
Moved to production on 1/11/15.
