### ISSUE TITLE
compound object full screen link

### ISSUE THREAD

**Issue by glewisorg** [FLVC/islandoratheme#17]
If you select Full Screen View without selecting one of the child objects it will dump you on an empty page. It makes sense since the parent object doesn’t have an OBJ datastream. It may be confusing to users who are expecting to get the full screen view of whatever that “first” item is.

**Comment by glewisorg** [comment]
I corrected Full Screen View and Download links for compound object on dev.  Let me know when it can move to test.

**Comment by mdemers** [comment]
This can move to test.

**Comment by glewisorg** [comment]
The changes have moved to test.  Changes are only in islandoratheme module so can move to production independent of the 7.x-1.4 update.

**Comment by mdemers** [comment]
Something odd is happening. It looks like I missed something on dev. The content div of certain content models in compound objects are dramatically changing sizes. So far I only see it occurring when mixing content models in compound objects. PDFs are shrunken down and audio and video are shrunken so much you can no longer see anything but padding.  

I don't know if this is a result of the changes made today or it's something we missed in 7.x-1.4. Can you back out today's changes on test?

**Comment by glewisorg** [comment]
I backed out today's changes from test.  The only difference was building the links so I wouldn't expect it to cause a problem.

**Comment by mdemers** [comment]
You're right, the problem is still on test. I can fix it by playing with the css if that's the easiest solution. I don't know what's causing it. New theming in the upgraded solution packs clashing with islandoratheme? You can put the full screen links back on test when you want and we'll divorce this other problem from this issue.

**Comment by glewisorg** [comment]
This change is back on test.

**Comment by mdemers** [comment]
This looks good. I think it's ready for production.

**Comment by glewisorg** [comment]
Moved to production on 1/11/15.
