### ISSUE TITLE
Place of Publication problem

### ISSUE THREAD

**Issue by mdemers** [FLVC/islandoratheme#25]
Value of originInfo/place/placeTerm@type="text" will not display in the presence of another 'place/placeTerm' where @type="code" subelement within the same 'originInfo' element. 

Ex:
```
<originInfo>
<place>
<placeTerm type="code" authority="marccountry">
pau</placeTerm>
</place>
<place>
<placeTerm type="text">Philadelphia, P.A.</placeTerm>
</place>
</originInfo>
```
I believe the above is an example of bad cataloging because pau and Philadelphia, Pa represent the same location and should be within a single 'place' element. If formatted this way Philadelphia, PA will display correctly. There is no way to replicate the above in our forms. Regardless, we still need the placeTerm@type="text" value to display no matter what. Is this possible? The entirety of the UCF Florida Heritage collection has this problem: https://ucf.digital.flvc.org/islandora/object/ucf%3Aflheritage

**Comment by lydiam** [comment]
Could this be folded into the other theming changes that we're trying to get into production by Monday?

**Comment by glewisorg** [comment]
Possibly.  Can you provide a link to an example object?  I went to the collection and tried a few objects but didn't see the problem.

**Comment by mdemers** [comment]
I found an example here: http://islandora7d.fcla.edu/islandora/object/islandora%3A4562#
```
 <originInfo>
    <place>
      <placeTerm type="code" authority="marccountry">xx</placeTerm>
    </place>
    <place>
      <placeTerm type="text">Tallahassee Fla</placeTerm>
    </place>
    <publisher>Bureau of Geology</publisher>
    <dateIssued encoding="marc">1972</dateIssued>
    <issuance>multipart monograph</issuance>
  </originInfo>
```

I'm not sure if it's the type or authority attribute throwing in off.

**Comment by mdemers** [comment]
Actually, it seems like the problem is that only the first place/placeTerm element gets displayed and placeTerm elements with the 'code' attribute aren't displayed -so if the placeTerm element with code is first neither will display. I don't think the codes should be displayed but it should be able to skip to and display the next placeTerm if there is one there.

I still don't think this is proper MODS but they are coming back as valid when I put them through the description service.

**Comment by glewisorg** [comment]
A fix for this is on dev.  Let me know if it's ready for test.

**Comment by mdemers** [comment]
Looks ready for test but I found another issue. 

According to the ISG spreadsheet, `<originInfo>` blocks should be repeatable but only the first block currently displays. Do you want that as a separate issue or to keep it here?

**Comment by glewisorg** [comment]
Separate issue.

**Comment by glewisorg** [comment]
This change has moved to test.

**Comment by glewisorg** [comment]
Moved to production on 1/11/15.
