### ISSUE TITLE
enhancements to collections display in preparation for PALMM site

### ISSUE THREAD

**Issue by lydiam** [FLVC/islandoratheme#30]
Because we're moving ahead with migrating PALMM materials from DigiTool into Islandora and working toward a plan for making an Islandora PALMM site public, Favenzio has been exploring options for enhancing collection display pages in Islandora.

His recommendations can be found at:  https://drive.google.com/file/d/0B9VDAj_UsqEXbExQdTlsWGJxWXc/view?usp=sharing

These will be discussed with ISG to determine if/how work on this will proceed.

**Comment by Favenzio** [comment]
As per the ISG meeting, I will begin work on these enhancements. Should have a prototype in a couple of weeks.

**Comment by Favenzio** [comment]
The enhancement to collections display have been completed.
