### ISSUE TITLE
Compound object content display

### ISSUE THREAD

**Issue by mdemers** [FLVC/islandoratheme#31]
The size of objects under the PDF, Video, and Audio Content Models is shrunken dramatically when part of a compound object. 

It doesn't appear to be a problem in production. FAUs Dances We Dance collection has many videos bundled with PDFs with no problem. I'll do some more variations on floradora to be sure.

Example object here: http://islandora7d.fcla.edu/islandora/object/islandora%3A4626

I think this issue can be resolved by removing the 'float: left' property in the content specific class of the theme css within the affected content models solution packs.

**Comment by glewisorg** [comment]
There are already some content model specific css files under islandoratheme/css/.  Are they already resetting the float value?  See audio.css for example:

[fclgnl@islandorad css]$ less audio.css 
.container { max-width: 100%; }
body.no-sidebars .islandora-audio-content { float: none; width: 100%; }
body.no-sidebars .islandora-audio-sidebar { float: none; width: 100%; }

**Comment by glewisorg** [comment]
Here was the most recent change to the css in the audio module.

https://github.com/Islandora/islandora_solution_pack_audio/commit/fa19132238648d5bfe6caec78d62c97b3ac32b97

**Comment by mdemers** [comment]
For some reason that markup in audio.css isn't applied to compound objects. Audio objects outside of compound objects are fine.

**Comment by glewisorg** [comment]
I added to the css in islandoratheme on dev.  Does compound look correct now?

**Comment by mdemers** [comment]
Yes, looks good. It can move to test when you're ready. I'm guessing this shouldn't move to production until 7.x-1.4 does?

**Comment by glewisorg** [comment]
Yes, this change should move to production with 7.x-1.4.  It's on test now.

**Comment by mdemers** [comment]
COs look good on production.
