### ISSUE TITLE
palmm-test:  collection list view and content object search results display

### ISSUE THREAD

**Issue by lydiam** [FLVC/islandoratheme#37]
palmm-test has been set up to display the PALMM collections in a "list" view, which is what users requested.  The benefit of this view is that it allows more characters to display in the collection description and is more similar to the display in palmm.fcla.edu.

The downside is that the content objects also display in "list" view instead of the faceted search results view.  Is there any way to present a list-like view of palmm:root collections while providing a search results view of content objects?

**Comment by glewisorg** [comment]
Favenzio put the code to redirect "bottom collections" to search results in a template called islandora-basic-collection-grid.tpl.php, so it was specific to the grid view.  I added the same code to the template for the list view.  The change is on dev and test.

**Comment by lydiam** [comment]
Gail, I’m not understanding this comment.  The list view of content objects in palmm:ycb doesn’t display with facets:  https://palmm-test.digital.flvc.org/islandora/object/palmm%3Aycb?display=list

Is there some setting that needs to be changed for this to take effect?

Lydia

**Comment by glewisorg** [comment]
You only get the search view on bottom collections if you are not logged in.  Are you currently logged in?  I opened a different browser to test as anonymous user.

**Comment by lydiam** [comment]
You’re right – I was logged in.  It looks great and gives us the best of both worlds for PALMM.  -- Lydia

**Comment by glewisorg** [comment]
Related to this issue, I changed the logic for "bottom" PALMM collections - if you are logged in and have the administrator role, you get the browse view.  Otherwise, you get search results.  This change is on dev, test, and prod.
