### ISSUE TITLE
palmm prod site:  full description tab displays only one palmm collection link at the bottom of the page

### ISSUE THREAD

**Issue by lydiam** [FLVC/islandoratheme#40]
A number of PALMM objects belong to 2 different PALMM collections:  most notably FGCU-owned objects.  However, in the Full Description tab only one PALMM collection displays.  Example:  https://palmm.digital.flvc.org/islandora/object/fgcu%3A21593#  has the following RELS-EXT:

```
    <isMemberOfCollection xmlns="info:fedora/fedora-system:def/relations-external#"   rdf:resource="info:fedora/fgcu:020304"></isMemberOfCollection>
     <fedora:isMemberOfCollection rdf:resource="info:fedora/palmm:sani">   </fedora:isMemberOfCollection>
     <fedora:isMemberOfCollection rdf:resource="info:fedora/palmm:fhp"></fedora:isMemberOfCollection>
```

But only the first PALMM collection, palmm:sani, displays in Full Description.

The downside to this situation is that the second collection, palmm:fhp, is a larger collection, and if the user is browsing the palmm:sani collection there's no direct way to see which PALMM collections the object is a member of (except for facets) and, more importantly, there's no direct way for the user to get from the smaller collection (palmm:sani) to the larger collection (palmm:fhp).

**Comment by glewisorg** [comment]
It's not actually displaying any of the PALMM collections, only the parent FGCU collection for the object.  There is code in islandoratheme to block PALMM collections from the full description.
Do you want the display to work differently under the PALMM site?

**Comment by lydiam** [comment]
I see.  The I misunderstood the function.  I believe that blocking PALMM collections from the Full Description was implemented so that PALMM collections wouldn't display in institutional sites, given that PALMM isn't public yet.  In addition, I believe that there was a problem with theming from the "originating site" was transferred when the collection link to another site was clicked.  So if you were in FSU and clicked on a PALMM collection link you'd be taken to the PALMM collection/site but the FSU theming still appeared.

For the time being I think it would be useful to not suppress PALMM collections from displaying in Full Description for the PALMM site.
