### ISSUE TITLE
<subject><name><namePart type="termsOf Address"> needs to display after <namePart>

### ISSUE THREAD

**Issue by lydiam** [FLVC/islandoratheme#8]
The spreadsheet says:

Display after given name, if no given name display after family name.  Precede with ", " (comma space)

However, there are cases when there is no @type="given" or @type="family" and we still need to display type="termsOfAddress" after <namePart no attribute> and before <namePart type="date">.

For example:

     <subject authority="lcsh">
     <name type="personal">
     <namePart type="termsOfAddress">Baron</namePart>
     <namePart>Dunsany, Edward John Moreton Drax Plunkett</namePart>
     <namePart type="date">1878-1957</namePart>
      </name>
      </subject>

Should display as:

Dunsany, Edward John Moreton Drax Plunkett, Baron, 1878-1957

**Comment by glewisorg** [comment]
Fixed this one too on dev.  Let me know if it's correct.

**Comment by lydiam** [comment]
I'll find additional examples, but at first testing this looks pretty good, except that there should be a comma after personal name and before termsOfAddress.  See: http://islandora7d.fcla.edu/islandora/object/islandora%3A4618.

**Comment by lydiam** [comment]
Looking into this more, and it looks like what's also needed is prepending of the comma in all cases.  Example: https://fsu.digital.flvc.org/islandora/object/fsu%3A92553#page/001/mode/2up=

MODS snippet:

<name type="personal" usage="primary">
<namePart>Elliott, W H</namePart>
<namePart type="termsOfAddress">sanitary inspector</namePart></name>

Resulting display:

Name(s): 	Elliott, W H sanitary inspector

That should display with a comma:

Name(s): 	Elliott, W H, sanitary inspector

I'm afraid that I no longer recall the exact details of this request, and it looks like it had been partially done.  It may be that the only remaining bit was to prepend the comma to termsOfAddress.  I see that no comma is prepended when given/family name is used (added to same object):

Name(s):	Motyka, Lydia Queen, 2011-2015

Should appear as:

Name(s):	Motyka, Lydia, Queen, 2011-2015

MODS snippet:

<name type="family">
<namePart type="given">Lydia</namePart>
<namePart type="family">Motyka</namePart>
<namePart type="termsOfAddress">Queen</namePart>
<namePart type="date">2011-2015</namePart>
</name>

I'd be satisfied that this was completed if a comma was prepended to termsOfAddress in all cases, regardless of name @type value.

**Comment by glewisorg** [comment]
That example is for mods->name->namePart.  This issue was for mods->subject->name->namePart.

**Comment by lydiam** [comment]
So sorry.  I missed that.

**Comment by glewisorg** [comment]
The correction I made for the subject->name->namePart issue was to append termsOfAddress to the end with a leading comma, and then append date to the end with a leading comma.  Before, termsOfAddress was added to the display in the same order that it appeared in the MODS.

Do you want me to make the same change for all other name->namePart elements?

**Comment by lydiam** [comment]
subject->name->namePart works perfectly:

http://islandora7d.fcla.edu/islandora/object/islandora%3A4619

Subject(s):	Lydia T. Motyka, Princess, 1999 - 2001
Lydia T. Motyka, Princess, 1999 - 2001
Motyka, Lydia, Princess, 2011-2015

Yes, please made the same change for all other name->namePart elements.  To the best of my knowledge name->namePart elements should be treated the same way.

**Comment by glewisorg** [comment]
This has been changed for all name->namePart elements on dev.

**Comment by lydiam** [comment]
It looks great.  Please put this on test for a final test.

**Comment by glewisorg** [comment]
It's moved to test.

**Comment by lydiam** [comment]
Looks good on test:  https://islandora-test.digital.flvc.org/islandora/object/islandora%3A3337

Ready for production.

**Comment by glewisorg** [comment]
Moved to production on 1/11/15.
